
export const TOAST_ERROR="app/TOAST_ERROR"
export const TOAST_SUCCESS="app/TOAST_SUCCESS"
export const TOAST_WARNING="app/TOAST_WARNING"


export const GET_CATEGORIES_REQUESTED="app/GET_CATEGORIES_REQUESTED"
export const GET_CATEGORIES_SUCCESS="app/GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAILED="app/GET_CATEGORIES_FAILED"

